### PR TITLE
fix empty data on test method screen

### LINKED ISSUE #62: No Data Is Shown In Generated Documentation on Latest Version Of laravel/framework
**Describe the bug**
After upgrading laravel/framework to its latest version (8.58as at the time of writing)
 I noticed that my documentation no longer have request and response data in them, just the test's  method title and description (if included with a docblock)

**To Reproduce**
* Run `php artisan enlighten` then look at generated docs and ensure everything is in order
* Upgrade laravel/framework (`composer update` , this should upgrade to the latest version
* Run `php artisan enlighten` again, check the generated docs, you should no longer see request/response data  in your endpoint
* Try downgrading. I have noticed that everything works fine at v8.52 - so run `composer require laravel/framework:8.52`

**Expected behavior**
Response and request data should be available when viewing documentation for an endpoint/method

### PR DESCRIPTION
**Pull request by eyounelson**
This fixes #62

### CODE REVIEW

**Comment by emmannl** [comment]
closing and sending new PR to a proper branch

**Comment by stephenjude** [comment]
@sileence when do you plan to tag a release?

**Comment by sileence** [comment]
Hi @emmannl @stephenjude thanks for your support. I'm planning to do the release tomorrow. But if you want to help me out, please use dev-main to test and confirm everything is working well while I fix php_cs :)

**Comment by stephenjude** [comment]
@sileence I have tested on dev branch and it works fine. Two of my codebase are currently pulling from dev-main branch. Thanks for the fix @emmannl

**Pull request merged**
