### PR TITLE
Laravel 9 support

### PR DESCRIPTION
**Pull request by stephenjude**
- Add Laravel 9 support

### CODE REVIEW

**Comment by stephenjude** [comment]
@sileence please review. I will wait for your response.

**Comment by stephenjude** [comment]
@sileence when are we getting Laravel 9 support?

**Review by ernestoliberio — APPROVED** [review]

**Comment by delino12** [comment]
[ernestoliberio](https://github.com/ernestoliberio) Trust you're doing great. @stephenjude Had some cool PR fix for Laravel 9 support. We can't wait to get enlightened.

**Comment by sileence** [comment]
thanks @stephenjude

**Pull request merged**
